language: php
install: composer install --no-dev
php:
  - '5.5'
  - '5.6'
  - '7.0'
script:
  - composer require --ignore-platform-reqs codeclimate/php-test-reporter dev-master
  - mkdir -p build/logs
  - cp tests/config_test.php config.php
  - phpunit --configuration tests/phpunit.xml --coverage-clover build/logs/clover.xml
  - ./vendor/bin/test-reporter
addons:
    code_climate:
        repo_token: ""

